export const SALT_ROUNDS = 'SALT_ROUNDS';
export const JWT_SECRET = 'JWT_SECRET';
export const ACCESS_TOKEN_JWT_EXPIRATION_TIME = 'ACCESS_TOKEN_JWT_EXPIRATION_TIME';
export const REFRESH_TOKEN_JWT_EXPIRATION_TIME = 'REFRESH_TOKEN_JWT_EXPIRATION_TIME';
export const LONG_JWT_EXPIRATION_TIME = 'LONG_JWT_EXPIRATION_TIME';
export const ACCESS_TOKEN_COOKIE_NAME = 'ACCESS_TOKEN_COOKIE_NAME';
export const REFRESH_TOKEN_COOKIE_NAME = 'REFRESH_TOKEN_COOKIE_NAME';

export default () => ({
  [SALT_ROUNDS]: Number(process.env[SALT_ROUNDS]) || 10,
  [JWT_SECRET]: process.env[JWT_SECRET] || 'jwt_secret',
  [ACCESS_TOKEN_JWT_EXPIRATION_TIME]: process.env[ACCESS_TOKEN_JWT_EXPIRATION_TIME] || '1h',
  [REFRESH_TOKEN_JWT_EXPIRATION_TIME]: process.env[REFRESH_TOKEN_JWT_EXPIRATION_TIME] || '7d',
  [LONG_JWT_EXPIRATION_TIME]: process.env[LONG_JWT_EXPIRATION_TIME] || '7d',
  [ACCESS_TOKEN_COOKIE_NAME]:
    process.env[ACCESS_TOKEN_COOKIE_NAME] || 'access_token',
  [REFRESH_TOKEN_COOKIE_NAME]:
    process.env[REFRESH_TOKEN_COOKIE_NAME] || 'refresh_token',
});
